### ISSUE TITLE
L-CR-LMc (Crubadan character n-gram feature)

### ISSUE THREAD

**Issue by goodmami** [xigt/lgid#12]
Implement the character n-gram feature for Crubadan data. Use the `character-n-gram-size` parameter in the config file and the character_ngrams() function in analyzers.py to compute the n-grams. Use the model stored at the `crubadan-language-model` path (defined in the config file).

**Comment by MackieBlackburn** [comment]
It looks like the files downloaded by `download-crubadan-data` into the `crubadan-language-model` directory only contain character trigrams and word unigrams and bigrams and this seems to be independent of what the config parameters are set to. It doesn't contain source data so there are no strings to use the character_ngrams() function on.

I can start reworking this to download crubadan source data rather than prebuilt LMs if you want.

**Comment by MackieBlackburn** [comment]
Each crubadan download contains only 3 prebuilt LMs and a list of URLs that were the source data. Maybe it would be best to use only the char trigrams and word unigrams and bigrams from the crubadan data, and rely on the ODIN data for the other ngrams specified in the config.

**Comment by goodmami** [comment]
Yes, I think that's a limitation of the data source. Forget the part in the description about using `characater-n-gram-size`, and always just use the Crubadan trigrams. It might be a good idea to put a separate `crubadan-character-n-gram-size` parameter in the config and set it to 3 (not that it's changeable, it's just so we don't have hard-coded values in the source), then use that parameter for the feature functions for crubadan data.
